basePath: '{swaggerBasePath}  // Dynamic base path placeholder'
definitions:
  model.AuthRequestDto:
    properties:
      emailOrNickname:
        type: string
      password:
        type: string
      rememberMe:
        type: boolean
    type: object
  model.Board:
    properties:
      createdBy:
        type: string
      id:
        type: integer
      name:
        type: string
      users:
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.BoardRequestDto:
    properties:
      name:
        type: string
    type: object
  model.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  model.FileResponseDto:
    properties:
      id:
        type: integer
    type: object
  model.JwtToken:
    properties:
      token:
        type: string
    type: object
  model.Permission:
    properties:
      description:
        type: string
      httpMethod:
        type: string
      id:
        type: integer
      url:
        type: string
    type: object
  model.Priority:
    enum:
    - HIGH
    - MEDIUM
    - LOW
    type: string
    x-enum-varnames:
    - High
    - Medium
    - Low
  model.Role:
    properties:
      id:
        type: integer
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/model.Permission'
        type: array
    type: object
  model.Status:
    enum:
    - NOT_STARTED
    - IN_PROGRESS
    - READY_FOR_TEST
    - DONE
    type: string
    x-enum-varnames:
    - NotStarted
    - InProgress
    - ReadyForTest
    - Done
  model.TaskRequestDto:
    properties:
      deadline:
        type: string
      name:
        type: string
      priority:
        $ref: '#/definitions/model.Priority'
    type: object
  model.TaskResponseDto:
    properties:
      assignedBy:
        $ref: '#/definitions/model.User'
      assignedTo:
        $ref: '#/definitions/model.User'
      attachmentFileId:
        items:
          type: integer
        type: array
      board:
        $ref: '#/definitions/model.Board'
      changedBy:
        $ref: '#/definitions/model.User'
      createdBy:
        $ref: '#/definitions/model.User'
      deadline:
        type: string
      id:
        type: integer
      name:
        type: string
      priority:
        $ref: '#/definitions/model.Priority'
      status:
        $ref: '#/definitions/model.Status'
      taskImageUrl:
        type: string
      taskVideoId:
        items:
          type: integer
        type: array
    type: object
  model.User:
    properties:
      acceptNotification:
        type: boolean
      boards:
        items:
          $ref: '#/definitions/model.Board'
        type: array
      description:
        type: string
      email:
        type: string
      fullName:
        type: string
      id:
        type: integer
      inactivatedDate:
        type: string
      isActive:
        type: boolean
      phoneNumber:
        type: string
      roles:
        items:
          $ref: '#/definitions/model.Role'
        type: array
      userName:
        type: string
    type: object
  model.UserRegistrationDto:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: '{swaggerHost}  // Dynamic host placeholder'
info:
  contact:
    email: support@your-email.com
    name: API Support
    url: http://www.your-support-url.com
  description: This is a sample API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://your.terms.of.service.url
  title: Your API Title
  version: "1.0"
paths:
  /v1/boards:
    post:
      consumes:
      - application/json
      description: Creates a new board based on the provided data
      parameters:
      - description: Board Request Data
        in: body
        name: BoardRequestDto
        required: true
        schema:
          $ref: '#/definitions/model.BoardRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: Board created successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new board
      tags:
      - Boards
  /v1/boards/{id}/access:
    post:
      consumes:
      - application/json
      description: Assign access to a specific board for a user
      parameters:
      - description: Board ID
        in: path
        name: id
        required: true
        type: integer
      - description: User ID
        in: query
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Access granted successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Give access to a board
      tags:
      - Boards
  /v1/boards/{userId}:
    get:
      consumes:
      - application/json
      description: Retrieve all boards associated with a specific user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of user boards
          schema:
            items:
              $ref: '#/definitions/model.Board'
            type: array
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user boards
      tags:
      - Boards
  /v1/files/delete/attachment/{attachmentFileId}:
    delete:
      description: Deletes an attachment file associated with a specific task
      parameters:
      - description: Attachment File ID
        in: path
        name: attachmentFileId
        required: true
        type: integer
      responses:
        "204":
          description: File deleted successfully
        "400":
          description: Invalid request or file ID
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete an attachment file
      tags:
      - Files
  /v1/files/download/attachment/{attachmentFileId}:
    get:
      description: Downloads an attachment file associated with a specific task
      parameters:
      - description: Attachment File ID
        in: path
        name: attachmentFileId
        required: true
        type: integer
      responses:
        "200":
          description: File downloaded successfully
        "400":
          description: Invalid request or file ID
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Download an attachment file
      tags:
      - Files
  /v1/files/get/task-image/{taskId}:
    get:
      consumes:
      - application/json
      description: Retrieves an image file associated with a specific task
      parameters:
      - description: Task ID
        in: path
        name: taskId
        required: true
        type: integer
      produces:
      - image/png
      - ' image/jpeg'
      - ' image/webp'
      responses:
        "200":
          description: Image file retrieved successfully
          schema:
            type: file
        "400":
          description: Invalid request or task ID
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Image not found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get task image
      tags:
      - Files
  /v1/files/stream/task-video/{taskVideoId}:
    get:
      consumes:
      - application/json
      description: Streams a video file associated with a specific task
      parameters:
      - description: Task Video ID
        in: path
        name: taskVideoId
        required: true
        type: integer
      produces:
      - video/mp4
      - ' video/webm'
      - ' video/ogg'
      responses:
        "200":
          description: Video file streamed successfully
          schema:
            type: file
        "400":
          description: Invalid request or task ID
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Video not found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Stream task video
      tags:
      - Files
  /v1/files/upload/attachment/{taskId}:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a file as an attachment for a specific task
      parameters:
      - description: Task ID
        in: path
        name: taskId
        required: true
        type: integer
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: File uploaded successfully
          schema:
            $ref: '#/definitions/model.FileResponseDto'
        "400":
          description: Invalid request or file
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Upload an attachment file
      tags:
      - Files
  /v1/files/upload/task-image/{taskId}:
    post:
      consumes:
      - multipart/form-data
      description: Uploads an image file associated with a specific task
      parameters:
      - description: Task ID
        in: path
        name: taskId
        required: true
        type: integer
      - description: Image file to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: File uploaded successfully
          schema:
            $ref: '#/definitions/model.FileResponseDto'
        "400":
          description: Invalid request or task ID
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Upload an image for a task
      tags:
      - Files
  /v1/files/upload/task-video/{taskId}:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a video file associated with a specific task
      parameters:
      - description: Task ID
        in: path
        name: taskId
        required: true
        type: integer
      - description: Video file to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: File uploaded successfully
          schema:
            $ref: '#/definitions/model.FileResponseDto'
        "400":
          description: Invalid request or task ID
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Upload a video for a task
      tags:
      - Files
  /v1/tasks/{boardId}:
    post:
      consumes:
      - application/json
      description: Create a new task for a specific board
      parameters:
      - description: Board ID
        in: path
        name: boardId
        required: true
        type: integer
      - description: Task details
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.TaskRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Task created successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a task
      tags:
      - Tasks
  /v1/tasks/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves the details of a specific task by ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Task details retrieved successfully
          schema:
            $ref: '#/definitions/model.TaskResponseDto'
        "400":
          description: Invalid request or task ID
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Task not found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get task details
      tags:
      - Tasks
  /v1/users/activate:
    get:
      consumes:
      - application/json
      description: Activates a user account using the provided activation token.
      parameters:
      - description: Activation token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: User successfully activated
          schema:
            type: string
        "400":
          description: Token is required
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Activate user account
      tags:
      - User
  /v1/users/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user by validating their credentials and returns
        a JWT token upon success.
      parameters:
      - description: authRequestDto
        in: body
        name: authRequestDto
        required: true
        schema:
          $ref: '#/definitions/model.AuthRequestDto'
      produces:
      - application/json
      responses:
        "200":
          description: JWT Token response
          schema:
            $ref: '#/definitions/model.JwtToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Authenticate user
      tags:
      - Authentication
  /v1/users/logout:
    get:
      consumes:
      - application/json
      description: Logs out the user by clearing all cookies and jwt token.
      produces:
      - application/json
      responses:
        "204":
          description: User successfully logged out
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Logout user
      tags:
      - User
  /v1/users/register:
    post:
      consumes:
      - application/json
      description: Registers a new user with the provided information.
      parameters:
      - description: userRegistrationDto
        in: body
        name: userRegistrationDto
        required: true
        schema:
          $ref: '#/definitions/model.UserRegistrationDto'
      produces:
      - application/json
      responses:
        "201":
          description: User successfully registered
          schema:
            type: string
        "400":
          description: Invalid request data
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Register a new user
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
